### ISSUE TITLE
Can't unmute after unmuting

### ISSUE THREAD

**Issue by zhemao** [Maato/volumeicon#11]
There's a bug with the mute / unmute functionality. After muting, you cannot unmute. Volumeicon indicates that the channel is unmuted, but there is no audio and opening alsamixer shows that the channel is still muted.

**Comment by gandalf3** [comment]
This is still occurring for me, and the patch/AUR package supplied no longer applies.

**Comment by alejandro-perez** [comment]
Use this
https://aur.archlinux.org/packages/xfce4-pulseaudio-plugin/

It works better.

**Comment by gandalf3** [comment]
@alejandro-perez Thanks, but I'm not sure how to use that with a non-xfce panel (I'm using tint2).

**Comment by gandalf3** [comment]
Just in case it helps, here are the versions I'm running:
pulseaudio 9.0
Volume Icon 0.5.1

I ended up disabling the mute shortcut in volumeicon, and setting up a separate mute shortcut with [pulseaudio-ctl](https://bbs.archlinux.org/viewtopic.php?id=124513).

Now it works well enough for me, though unmuting by clicking on volumeicon still doesn't work of course.
