### ISSUE TITLE
volumeicon: alsa_backend.c:92: asound_get_volume: Assertion `m_elem != ((void *)0)' failed.

### ISSUE THREAD

**Issue by morfikov** [Maato/volumeicon#32]
I have the following error when my openbox tries to start volumeicon:

    volumeicon: alsa_backend.c:92: asound_get_volume: Assertion `m_elem != ((void *)0)' failed.

When volumeicon is started manually, it works without a problem. The problem lies in indexes of sound cards, the ones you can add via `/etc/modprobe.d/alsa-base.conf` . I set order of my sound cards because I usually have two of them:

    options snd-ca0106 index=0
    options snd-hda-intel index=1

If I have both cards enabled, everything works as expected, but when I disable the card with `index=0`, so there will be only one card in the system with `index=1`, I get the problem in question.

For now I've changed the index to 0 in order to be able to start volumeicon automatically, and it works so far.

**Comment by Maato** [comment]
I'm not entirely sure but I believe this was fixed in commit: 395d4d7ea118f917bb090e2cb927a1fef595fe67.
