### ISSUE TITLE
build issue on debian jessie

### ISSUE THREAD

**Issue by rejon** [Maato/volumeicon#43]
Received these errors, and could not get away from them, so went ahead and just did a ./configure and continued with make and sudo make install and everything worked...

    $ ./autogen.sh 
    Copying file po/Makefile.in.in

    Please add the files
      codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
      progtest.m4
    from the /usr/share/aclocal directory to your autoconf macro directory or directly to your aclocal.m4 file.
    You will also need config.guess and config.sub, which you can get from
    ftp://ftp.gnu.org/pub/gnu/config/.

**Comment by Maato** [comment]
Its does not appear to be an error, and can safely be ignored. However, it is confusing so I've addressed this by silencing its output in commit c46a384eb8c9bb41b134df0d0e84ed02cd49ecdc.
