### ISSUE TITLE
Does not work with GTK+ 3.20

### ISSUE THREAD

**Issue by jackjjkcaj** [Maato/volumeicon#58]
Command line output can be seen here: http://pastebin.com/Cy9Mz0ZT

**Comment by dglava** [comment]
It works for me, using GTK 3.20.3.
Are those errors actually preventing it from running or are they warning messages? Try using the default Adwaita theme or a 3.20 compatible theme and see if it resolves it.

**Comment by jackjjkcaj** [comment]
The error was with the Arc GTK+ theme. After an update, volume icon works as expected.
