### ISSUE TITLE
Missing manual page

### ISSUE THREAD

**Issue by alive4ever** [Maato/volumeicon#59]
A manual page is standard reference document for POSIX applications. `volumeicon` didn't have a manual page.

Please consider adding a manpage for better user reference.

**Comment by fpytloun** [comment]
help2man tool may be handy here :-)
https://www.gnu.org/software/help2man/

**Comment by alive4ever** [comment]
I've created a pull request for manual page, written in pod. #60 
Modification to the build system is needed so that the manual page is generated and installed on build.

**Comment by alive4ever** [comment]
Ping @Maato. Is this repository still maintained?
