### ISSUE TITLE
when quitting neighbor tray app, volumeicon's Icon gets the icon of its new neighbor

### ISSUE THREAD

**Issue by revast** [Maato/volumeicon#65]
![test](https://cloud.githubusercontent.com/assets/8189198/26069636/f314fe6c-39a1-11e7-9802-2734549832f1.gif)

happens in xfce4-panel 4.12.0-3ubuntu2, Ubuntu 16.04 LTS, also with current master, in the gif I use the scrollwheel to bring back the volumeicon's Icon. This also happens when I quit another app which is not the direct neighbor, as long as the app is right-side of volumeicon's Icon, it gets the icon of its right-side neighbor

**Comment by dglava** [comment]
That seems to be a taskbar related issue, no? Works fine for me. I'm using the latest build of Volumeicon from master (the taskbar is tint2).
https://s1.webmshare.com/EBMgg.webm

Have you tried it with a different taskbar? See if it persists in a different taskbar. If not, it's most likely an xfce4-panel problem.

**Comment by nkoep** [comment]
Any news on this @revast? Does the issue persist? If not I think we'll close this issue for the moment

**Comment by revast** [comment]
sorry for answering this late, yeah seems to be xfce-panel related.
